#!/usr/bin/env python3
"""Build the RFdiffusionAA cloud input: carrier protein + corrected L4F anchor.

WHY a carrier protein (not the bare ligand)
-------------------------------------------
RFdiffusionAA's inference/utils.py `process_target()` builds the contig frame
from protein ATOM/CA records (and centers on the CA centroid); a ligand-only PDB
has no CA and breaks it. For a DE-NOVO contig (e.g. ['120-120'], no chain motif
refs) the carrier protein is parsed and then DISCARDED by `insert_contig` --
only the ligand (is_sm) is kept as the motif the fresh pocket is built around.
This mirrors the upstream README example, which passes the full 7v11 protein with
a ['150-150'] contig to design a de-novo binder to the OQO ligand.

We reuse scaffold_clean.pdb chain A (a real 172-res protein) as the carrier and
place the anchor in its pocket (cosmetic for a de-novo contig; also leaves the
file usable for a future motif-scaffold run). The ligand chemistry is identical
to the anchor-fix GATE deliverable data/raw/ligand_L4F.pdb: 8 carbons + the
single para-F, resname PFF, with CONECT (OpenBabel reads element + CONECT; no
CCD lookup -- verified in rf_diffusion_all_atom/aa_model.py parse_mol).

OUTPUT (tracked, so the corrected F-ligand is *baked into* the cloud package)
  cloud/rfdiffusion_aa/input_L4F_pocket.pdb
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np
from prep_ligandmpnn_input import (parse_pdb_atoms, kabsch, het_line, CORRESP,
                                   REPO, SCAFFOLD, LIG_L4F)

OUTDIR = os.path.join(REPO, "cloud", "rfdiffusion_aa")
OUT = os.path.join(OUTDIR, "input_L4F_pocket.pdb")
LIGCODE = "PFF"          # must match inference.ligand on the run command
LIGCHAIN = "B"
LIGRESSEQ = 1

# side-chain connectivity (the 9 atoms we ship; subset of the PFF graph)
SIDECHAIN_BONDS = [
    ("CA", "CB"), ("CB", "CG"),
    ("CG", "CD1"), ("CG", "CD2"),
    ("CD1", "CE1"), ("CD2", "CE2"),
    ("CE1", "CZ"), ("CE2", "CZ"),
    ("CZ", "F"),
]


def main():
    os.makedirs(OUTDIR, exist_ok=True)
    scaf = parse_pdb_atoms(SCAFFOLD)
    chainA = [a for a in scaf if a["chain"] == "A" and a["record"] == "ATOM"]
    phe8 = {a["name"]: a["xyz"] for a in scaf if a["chain"] == "B" and a["resseq"] == 8}

    lig = parse_pdb_atoms(LIG_L4F)
    lig_by_name = {a["name"]: a for a in lig}

    # rigid-place the anchor onto the docked PHE8 side chain (same fit as the
    # LigandMPNN prep; F rides along on the transform)
    P = np.array([lig_by_name[ln]["xyz"] for ln, _ in CORRESP])
    Q = np.array([phe8[pn] for _, pn in CORRESP])
    R, t, rmsd = kabsch(P, Q)
    placed = [{**a, "xyz": (R @ a["xyz"]) + t} for a in lig]
    print(f"[kabsch] anchor -> pocket RMSD = {rmsd:.3f} A")

    # serials: ligand HETATM continue after the protein to avoid id collisions
    base = len(chainA)
    serial = {a["name"]: base + i + 1 for i, a in enumerate(placed)}

    n_F = sum(1 for a in placed if a["element"] == "F")
    n_O = sum(1 for a in placed if a["element"] == "O")
    names = [a["name"] for a in placed]

    with open(OUT, "w", newline="\n") as fh:
        fh.write("REMARK  RFdiffusionAA cloud input: carrier protein (scaffold chain A,\n")
        fh.write("REMARK  discarded by a de-novo contig) + corrected L4F anchor (resname\n")
        fh.write(f"REMARK  {LIGCODE}). Generated by src/prep_rfdiffusion_aa_input.py.\n")
        for a in chainA:
            fh.write(a["raw"] + "\n")
        fh.write("TER\n")
        for a in placed:
            fh.write(het_line(serial[a["name"]], a["name"], LIGCODE, LIGCHAIN,
                              LIGRESSEQ, a["xyz"], a["element"]))
        present = set(names)
        for n in names:
            neigh = [b for (x, y) in SIDECHAIN_BONDS
                     for (a_, b) in [(x, y), (y, x)]
                     if a_ == n and b in present]
            if neigh:
                refs = "".join(f"{serial[m]:>5}" for m in neigh)
                fh.write(f"CONECT{serial[n]:>5}{refs}\n")
        fh.write("END\n")

    print(f"[write] {OUT}")
    print(f"        carrier: chain A, {len(chainA)} protein atoms")
    print(f"        ligand : resname {LIGCODE}, {len(placed)} atoms "
          f"({names}); F count={n_F}; O count={n_O}")
    assert n_F == 1, "expected exactly one para-F"
    assert n_O == 0, "expected zero oxygens (side-chain-centric anchor)"
    assert len(placed) == 9, "expected 9 ligand heavy atoms"
    print("        CHECK: exactly 1 para-F, 0 O, 9 heavy atoms -> matches the GATE ligand")


if __name__ == "__main__":
    main()
