#!/usr/bin/env python3
"""Build the chemically-correct fluoroaromatic anchor for the ligand-aware path.

WHY this exists
---------------
The frozen Key anchor baked into data/raw/scaffold_clean.pdb is malformed. It was
produced by src/graft_residue.py, which auto-names atoms by element count
(O1/O2/C3..C9), keeps a *second* carboxylate oxygen, and keeps explicit hydrogens
-- then drops the whole residue into a MID-peptide position (Key position 8 of 15).
That is chemically wrong for a mid-chain residue and unusable as a clean ligand for
ligand-aware design (RFdiffusionAA / LigandMPNN), where the para-fluorine must be
the explicit discriminating atom.

This script regenerates the anchor from the authoritative source: the RCSB Chemical
Component Dictionary entry **PFF = 4-FLUORO-L-PHENYLALANINE** (formula C9 H10 F N O2).
The heavy-atom ideal coordinates below were copied from the verified PFF.cif and
geometry-checked (see _selfcheck()). Standard CCD atom names; single para-F at CZ;
no hydrogens.

REPRESENTATION (chosen: side-chain-centric -- "Option A")
---------------------------------------------------------
In the real Key, L4F is residue 8 of 15 -- MID-peptide. It has no free carboxylate
and no free amino terminus. For ligand-aware *pocket design* we therefore present
ONLY the side chain that protrudes into the pocket plus CA as the backbone-exit cap:

    CA  CB  CG  CD1  CD2  CE1  CE2  CZ  F      (L4F, 9 heavy atoms)

Dropping N/C/O/OXT removes free-terminus charges that (a) do not exist mid-peptide
and (b) would let RFdiffusionAA bury a charged carboxylate and let that dominate the
binding energetics over the subtle C-F discrimination we are actually testing. Zero
oxygens, so "no extra O" is satisfied trivially.

A "residue" mode (N CA C O ... F, single correct carbonyl O, no OXT) is retained for
later all-atom/physics complex assembly, but is NOT generated by default.

OUTPUTS (data/ is gitignored -> non-destructive)
  data/raw/ligand_L4F.pdb  -- the discriminating ligand (PFF side chain, real para-F)
  data/raw/ligand_PHE.pdb  -- the F-absent control (identical minus the F atom)

The two files are byte-for-byte identical except the L4F file carries one extra
HETATM (the F) and its CONECT -- isolating the single-atom difference the designed
pocket must discriminate.

This script ONLY writes the standalone ligand blocks. Wiring the ligand into
LigandMPNN / the RFdiffusionAA cloud package is a downstream step.
"""

import argparse
import math
import os

# --- Authoritative geometry: PFF (4-fluoro-L-phenylalanine) CCD ideal coords ---
# (name, element, x, y, z). Heavy atoms only -- hydrogens are intentionally omitted.
PFF_ATOMS = [
    ("N",   "N", -0.040, -1.210,  0.053),  # backbone amino N
    ("CA",  "C",  1.172, -1.709,  0.652),  # alpha carbon (L-config); side-chain attach cap
    ("C",   "C",  1.083, -3.207,  0.905),  # backbone carbonyl C
    ("O",   "O",  0.040, -3.770,  1.222),  # backbone carbonyl O
    ("OXT", "O",  2.247, -3.882,  0.744),  # free-acid 2nd carboxylate O (C-term only)
    ("CB",  "C",  1.484, -0.975,  1.962),  # beta carbon
    ("CG",  "C",  2.940, -1.060,  2.353),  # ring ipso (attached to CB)
    ("CD1", "C",  3.369, -2.109,  3.149),
    ("CD2", "C",  3.820, -0.086,  1.907),
    ("CE1", "C",  4.715, -2.188,  3.510),
    ("CE2", "C",  5.166, -0.165,  2.268),
    ("CZ",  "C",  5.613, -1.216,  3.069),  # ring para (bears the fluorine)
    ("F",   "F",  6.904, -1.291,  3.415),  # the discriminating para-fluorine
]

# Heavy-atom connectivity (covalent bonds) by atom name.
PFF_BONDS = [
    ("N", "CA"), ("CA", "C"), ("CA", "CB"),
    ("C", "O"), ("C", "OXT"),
    ("CB", "CG"),
    ("CG", "CD1"), ("CG", "CD2"),
    ("CD1", "CE1"), ("CD2", "CE2"),
    ("CE1", "CZ"), ("CE2", "CZ"),
    ("CZ", "F"),
]

# Atom subsets per representation (F handled separately via include_f).
MODE_ATOMS = {
    # Option A -- side-chain + CA cap; zero backbone oxygens. The design ligand.
    "sidechain": ["CA", "CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ", "F"],
    # Option B -- corrected mid-peptide residue; one correct carbonyl O, no OXT.
    "residue":   ["N", "CA", "C", "O", "CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ", "F"],
}
MODE_FILES = {
    "sidechain": ("ligand_L4F.pdb", "ligand_PHE.pdb"),
    "residue":   ("anchor_residue_L4F.pdb", "anchor_residue_PHE.pdb"),
}

CHAIN = "B"
RESSEQ = 1


def _dist(a, b):
    return math.sqrt(sum((a[i] - b[i]) ** 2 for i in range(3)))


def _pdb_atom_line(serial, name, resname, x, y, z, element, bfac=1.00):
    # PDB fixed-column HETATM record. Atom name occupies cols 13-16: a 1-2 char
    # element gets one leading pad space; a 4-char name starts at col 13.
    name4 = name.ljust(4) if len(name) == 4 else (" " + name).ljust(4)
    return (f"HETATM{serial:>5} {name4}{'':1}{resname:>3} {CHAIN:1}{RESSEQ:>4}{'':1}   "
            f"{x:8.3f}{y:8.3f}{z:8.3f}{1.00:6.2f}{bfac:6.2f}          {element:>2}")


def _conect_lines(names, serial):
    present = set(names)
    neigh = {n: [] for n in names}
    for a, b in PFF_BONDS:
        if a in present and b in present:
            neigh[a].append(b)
            neigh[b].append(a)
    lines = []
    for n in names:
        if neigh[n]:
            refs = "".join(f"{serial[m]:>5}" for m in neigh[n])
            lines.append(f"CONECT{serial[n]:>5}{refs}")
    return lines


def write_ligand(path, resname, keep, include_f, mode):
    coord = {n: (e, x, y, z) for n, e, x, y, z in PFF_ATOMS}
    names = [n for n in keep if include_f or n != "F"]
    serial = {n: i + 1 for i, n in enumerate(names)}
    lines = [
        "REMARK   generated by src/prep_ligand.py from PFF CCD ideal coords",
        f"REMARK   mode={mode}  resname {resname}  "
        f"{'WITH para-F (L4F)' if include_f else 'NO F (PHE control)'}",
    ]
    for n in names:
        e, x, y, z = coord[n]
        lines.append(_pdb_atom_line(serial[n], n, resname, x, y, z, e))
    lines.extend(_conect_lines(names, serial))
    lines.append("END")
    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    return names


def _selfcheck():
    """Validate the source coords (mode-independent) so the anchor can be eyeballed."""
    a = {n: (x, y, z) for n, _e, x, y, z in PFF_ATOMS}
    print("PFF (4-fluoro-L-phenylalanine) source coords -- geometry self-check")
    print("-" * 62)
    print(f"  CZ-F  bond   : {_dist(a['CZ'], a['F']):.3f} A   (aromatic C-F ~1.34)")
    print(f"  CB-CG bond   : {_dist(a['CB'], a['CG']):.3f} A   (Csp3-Caro ~1.51)")
    print(f"  CA-CB bond   : {_dist(a['CA'], a['CB']):.3f} A   (~1.53)")
    print(f"  CG-CD1 bond  : {_dist(a['CG'], a['CD1']):.3f} A   (aromatic ~1.39)")
    print(f"  CG..CZ (para): {_dist(a['CG'], a['CZ']):.3f} A   (1,4 across ring ~2.79)")
    ring = ["CG", "CD1", "CD2", "CE1", "CE2", "CZ"]
    nearest = min(ring, key=lambda r: _dist(a[r], a["F"]))
    print(f"  F nearest ring C: {nearest}  ({'PARA - correct' if nearest == 'CZ' else 'WRONG'})")
    print()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out-dir", default="data/raw",
                    help="Where to write the ligand PDBs.")
    ap.add_argument("--mode", choices=list(MODE_ATOMS), default="sidechain",
                    help="sidechain (Option A, design ligand; default) or "
                         "residue (Option B, mid-peptide residue for complex assembly).")
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    _selfcheck()

    keep = MODE_ATOMS[args.mode]
    f_name, phe_name = MODE_FILES[args.mode]
    l4f = os.path.join(args.out_dir, f_name)
    phe = os.path.join(args.out_dir, phe_name)
    a_l4f = write_ligand(l4f, "PFF", keep, include_f=True, mode=args.mode)
    a_phe = write_ligand(phe, "PHE", keep, include_f=False, mode=args.mode)
    n_o = sum(1 for n in a_l4f if n in ("O", "OXT"))
    print(f"mode={args.mode}")
    print(f"wrote {l4f}  ({len(a_l4f)} heavy atoms, resname PFF, para-F present, O count={n_o})")
    print(f"wrote {phe}  ({len(a_phe)} heavy atoms, resname PHE, F removed = control)")
    print(f"  L4F atoms: {' '.join(a_l4f)}")
    print("\nThe two files differ by exactly one atom (the para-F) + its CONECT.")


if __name__ == "__main__":
    main()
